pub const INITIAL_WINDOW_WIDTH: i32 = 640;
pub const INITIAL_WINDOW_HEIGHT: i32 = 480;

pub const INITIAL_TEXT_BOX_WIDTH: f32 = 500.0;
pub const INITIAL_TEXT_BOX_HEIGHT: f32 = 100.0;

pub const TEXT_BOX_X_POSITION: f32 = INITIAL_WINDOW_WIDTH as f32 / 2.0 - INITIAL_TEXT_BOX_WIDTH / 2.0;
pub const TEXT_BOX_Y_POSITION: f32 = INITIAL_WINDOW_HEIGHT as f32 / 2.0 - INITIAL_TEXT_BOX_HEIGHT / 2.0;
pub const TEXT_BOX_LINE_THICKNESS: f32 = 2.0;